/**:
  # Global Parameters
  ros__parameters:
    tf_timeout_threshold: 0.5

/**:
  # Basic Robotics Functions
  # Platform
  platform:
    ros__parameters:
      max_thrust: 29.0
      min_thrust: 0.15
      # Indoor RealSense or Motion Capture
      external_odom: true

  # State Estimator
  state_estimator:
    ros__parameters:
      # Indoor Raw Odometry
      # plugin_name: "raw_odometry"
      # # Indoor RealSense
      # plugin_name: "raw_odometry"
      # odom_topic: "sensor_measurements/realsense/odom"
      # # Indoor Motion Capture
      plugin_name: "mocap_pose"
      mocap_topic: "/mocap/rigid_bodies"
      twist_smooth_filter_cte: 0.1
      orientation_smooth_filter_cte: 0.1

      # # Outdoor (GPS) Raw Odometry
      # plugin_name: "raw_odometry"
      # use_gps: true
      # set_origin_on_start: true

  # Behaviors Motion
  TakeoffBehavior:
    ros__parameters:
      # takeoff_plugin_name: "takeoff_plugin_speed"
      takeoff_plugin_name: "takeoff_plugin_position"
      # takeoff_plugin_name: "takeoff_plugin_trajectory"
  LandBehavior:
    ros__parameters:
      land_plugin_name: "land_plugin_speed"
      # land_plugin_name: "land_plugin_trajectory"
  GoToBehavior:
    ros__parameters:
      go_to_plugin_name: "go_to_plugin_position"
      # go_to_plugin_name: "go_to_plugin_trajectory"
  FollowPathBehavior:
    ros__parameters:
      follow_path_plugin_name: "follow_path_plugin_position"
      # follow_path_plugin_name: "follow_path_plugin_trajectory"

  # Hardware Interfaces
  # usb_camera_interface:
  #   ros__parameters:
  #     device: "/dev/video0"
  #     framerate: 30.0 # Frame rate of the camera (fps)
  #     # Camera configuration
  #     camera_transform:
  #       parent_frame: "base_link" # Parent frame of the camera
  #       x: 0.1 # Translation in x (m)
  #       y: 0.0 # Translation in y (m)
  #       z: 0.03 # Translation in z (m)
  #       roll: -1.57079632679 # Rotation around x (rad)
  #       pitch: 0.0 # Rotation around y (rad)
  #       yaw: -1.57079632679 # Rotation around z (rad)

# Specific Parameters for each drone
drone1/state_estimator:
  ros__parameters:
    rigid_body_name: "19"

drone1:
  mavros/mavros_node:
    ros__parameters:
      fcu_url: "/dev/ttyACM0:57600" # Autopilot address for connection
      gcs_url: "udp://@192.168.0.31:14550" # Ground Control Station address
      tgt_system: 1 # Target system ID = Instance + 1
      tgt_component: 1 # Target component ID
      log_output: "screen"
      odom_frame: "drone1/odom"
      map_frame: "drone1/map"

/drone1/mavros/global_position:
  ros__parameters:
    frame_id: "drone1/map"               # origin frame
    child_frame_id: "drone1/base_link"   # body-fixed frame
    tf.frame_id: "drone1/map"            # TF frame_id
    tf.global_frame_id: "earth"   # TF earth frame_id
    tf.child_frame_id: "drone1/base_link"  # TF child_frame_id

/drone1/mavros/imu:
  ros__parameters:
    frame_id: "drone1/base_link"

/drone1/mavros/local_position:
  ros__parameters:
    frame_id: "drone1/map"
    tf.frame_id: "drone1/map"
    tf.child_frame_id: "drone1/base_link"

/drone1/mavros/setpoint_attitude:
  ros__parameters:
    tf.frame_id: "drone1/map"

/drone1/mavros/setpoint_position:
  ros__parameters:
    tf.frame_id: "drone1/map"

/drone1/mavros/odometry:
  ros__parameters:
    fcu.odom_parent_id_des: "drone1/odom"        # desired parent frame rotation of the FCU's odometry
    fcu.odom_child_id_des: "drone1/base_link"    # desired child frame rotation of the FCU's odometry
    fcu.map_id_des: "drone1/map"

